aws:
  region: us-east-1
  endpoint: http://localhost:4566
  access_key: test
  secret_key: test

kinesis:
  stream_name: test-stream

producer:
  batch_size: 10
  batch_delay_ms: 1000
  total_messages: 0

consumer:
  assignment_mode: kcl
  application_name: kds-rebalance-consumer
  worker_id: worker-3
  max_records: 10
  call_process_records_even_for_empty_list: false
  poll_interval_ms: 1000
